Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [110]:
import numpy as np

In [111]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
numbers=[1,2,3,4,5]
arr= np.array(numbers)
print(arr)
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
twoD= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(twoD)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [112]:
# Write a NumPy function to create an array with random values of shape [3,4]
ran=np.random.rand(3,4)
print(ran)
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
arr1=np.zeros((3,4))
print(arr1)
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
arr2=np.ones((3,4))
print(arr2)

[[0.84058652 0.32315625 0.60074972 0.11908013]
 [0.45567386 0.70730164 0.15550027 0.59345217]
 [0.28848682 0.47550081 0.34795617 0.99869316]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [113]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
even= np.arange(3,18)
print(even)
# Hint : Use np.arange or np.linspace

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


### Basic array operations
- algebraic operations
- logical operations

In [114]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [115]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
sum=np.add(a,b)
print(sum)
diff=np.subtract(a,b)
print(diff)
pdt=np.multiply(a,b)
print(pdt)
div=np.divide(a,b)
print(div)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [116]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
alongZERO=np.sum(a,axis=0)
print(alongZERO)
# Write a NumPy function to get the sum of the array 'a' along axis=1
alongONE=np.sum(a,axis=1)
print(alongONE)

[ 6 17 14]
[10 13 14]


In [117]:
# Write a NumPy function to reverse the array 'a'
rev=np.flip(a)
print(rev)
# Write a NumPy function to reverse the array 'a' along axis=0
rev1=np.flip(a,axis=0)
print(rev1)
# Write a NumPy function to reverse the array 'a' along axis=1
rev2=np.flip(a,axis=1)
print(rev2)

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [118]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])

b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [119]:
# Write a NumPy function to sort the array 'a'
sort1=np.sort(a)
print(sort1)
# Write a NumPy function to sort the array 'a' along axis=0
sort2=np.sort(a,axis=0)
print(sort2)
# Write a NumPy function to sort the array 'a' along axis=1
sort3=np.sort(a,axis=1)
print(sort3)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
sort4=np.sort(a,axis=0)[::-1]
print(sort4)

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [120]:
# Write a NumPy function to argsort the array along axis=0
sort5=np.argsort(a,axis=0)
print(sort5)
# Write a NumPy function to argsort the array along axis=1
sort6=np.argsort(a,axis=1)
print(sort6)

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [121]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
conc1= np.concatenate((a,b))
print(conc1)
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
conc2= np.concatenate((a,b),axis=0)
print(conc2)
# Note: You can do the same function using stacking, discover and try that :)
stack1=np.vstack((a,b))   #along columns
print(stack1)  #along columns
stack2=np.hstack((a,b))   #along rows
print(stack2)

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8 11 16 18]
 [ 9  3  1 90 37 81]
 [ 1  8  5 61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [122]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [123]:
# Write a NumPy function to get the Number of dimensions
d=np.ndim(a)
print(d)
# Write a NumPy function to get the Shape of the array
sha=np.shape(a)
print(sha)
# Write a NumPy function to get the Size of the array
siz=np.size(a)
print(siz)

2
(3, 3)
9


In [124]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
reshaped=np.reshape(a,(1,9))
print(reshaped)

[[4 6 8 9 3 1 1 8 5]]


In [125]:
# Write a NumPy function to add a new axis to the array 'a'

# Note : Show atleast two different ways of doing this
#1st way:
ThreeD=a[np.newaxis]
print(np.ndim(ThreeD))
print(np.shape(ThreeD))
#2nd way:
ThreeD2= np.expand_dims(a,axis=1)
print(np.ndim(ThreeD2))
print(np.shape(ThreeD2))

3
(1, 3, 3)
3
(3, 1, 3)


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [126]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [127]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
print(a[1,1])
print(a[1:3,0:2])
# Show all three - indexing by a integer, indexing by a tuple, using range
#indexing by integer
print(a[[0,1,2],[0,1,2]])
#indexing by a tuple
print(a[(0,1,2)[0]])
#indexing using range
for i in range(3):
  for j in range(3):
     print(a[i][j])

3
[[0 3]
 [1 8]]
[4 3 5]
[4 6 0]
4
6
0
0
3
1
1
8
5


In [150]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
selected= np.extract([a>4],[a])
print(selected)
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
selectedM=np.extract([(a>4) & (a%2==0)],[a])
print(selectedM)

[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [129]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [130]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
copied=np.copy(a)
copied+=1
print(copied)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [131]:
import pandas as pd

In [132]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [133]:
# Write a Pandas function to drop rows that contain a missing value.

dframe=pd.DataFrame(iris_2d)
afterDrop=dframe.dropna()
print(afterDrop)

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]


In [134]:
# Write a Pandas function to find the correlation between the first two columns.
correlation=dframe[0].corr(dframe[1])
print(correlation)

-0.10936924995064937


In [135]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
mean=dframe[2].mean()
print(mean)
median=dframe[2].median()
print(median)
std=dframe[2].std()
print(std)


3.758666666666666
4.35
1.7644204199522626


In [151]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

dframe['Volume'] = (np.pi * dframe[2] * dframe[0]**2) / 3
print(dframe)

       0    1    2    3      Volume
0    5.1  3.5  1.4  0.2   38.132652
1    4.9  3.0  1.4  0.2   35.200498
2    4.7  3.2  1.3  0.2   30.072372
3    4.6  3.1  1.5  0.2   33.238050
4    5.0  3.6  1.4  0.2   36.651914
..   ...  ...  ...  ...         ...
145  6.7  3.0  5.2  2.3  244.445230
146  6.3  2.5  5.0  1.9  207.816354
147  6.5  3.0  5.2  2.0  230.069302
148  6.2  3.4  5.4  2.3  217.373079
149  5.9  3.0  5.1  1.8  185.910028

[150 rows x 5 columns]


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [137]:
import numpy as np
x = np.arange(4, dtype=np.int64)

In [138]:
copy=np.ones_like(x)
print(copy)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [139]:
arr=np.array([1,2,3,4,5,6,7,8,9])
split=np.split(arr,[4,6])
print(split)

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [140]:
x=np.arange(0,10)
x=x.reshape(2,5)
print(x)

max_value = np.max(x, axis=1)
max_indices = np.argmax(x, axis=1)
print(max_value)
print(max_indices)

min_value = np.min(x, axis=1)
min_indices = np.argmin(x, axis=1)
print(min_value)
print(min_indices)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[4 9]
[4 4]
[0 5]
[0 0]


### Pandas

Run the following load command and solve the following questions

In [141]:
import pandas as pd

In [142]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [143]:
dataFrame=pd.DataFrame(iris)
print(dataFrame)


          0       1       2       3                  4
0    b'5.1'  b'3.5'  b'1.4'  b'0.2'     b'Iris-setosa'
1    b'4.9'  b'3.0'  b'1.4'  b'0.2'     b'Iris-setosa'
2    b'4.7'  b'3.2'  b'1.3'  b'0.2'     b'Iris-setosa'
3    b'4.6'  b'3.1'  b'1.5'  b'0.2'     b'Iris-setosa'
4    b'5.0'  b'3.6'  b'1.4'  b'0.2'     b'Iris-setosa'
..      ...     ...     ...     ...                ...
145  b'6.7'  b'3.0'  b'5.2'  b'2.3'  b'Iris-virginica'
146  b'6.3'  b'2.5'  b'5.0'  b'1.9'  b'Iris-virginica'
147  b'6.5'  b'3.0'  b'5.2'  b'2.0'  b'Iris-virginica'
148  b'6.2'  b'3.4'  b'5.4'  b'2.3'  b'Iris-virginica'
149  b'5.9'  b'3.0'  b'5.1'  b'1.8'  b'Iris-virginica'

[150 rows x 5 columns]


Q4 Write a Pandas function to find the count of unique species.

In [144]:
count=dataFrame.nunique()
print(count)

0    35
1    23
2    43
3    22
4     3
dtype: int64


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [145]:
    dataFrame[2]=dataFrame[2].astype(float)
    bins = [0, 2.9, 4.9, float('inf')]
    labels = ['small', 'medium', 'large']

    dataFrame['petal_length'] = pd.cut(dataFrame[2], bins=bins, labels=labels)
    print(dataFrame)




          0       1    2       3                  4 petal_length
0    b'5.1'  b'3.5'  1.4  b'0.2'     b'Iris-setosa'        small
1    b'4.9'  b'3.0'  1.4  b'0.2'     b'Iris-setosa'        small
2    b'4.7'  b'3.2'  1.3  b'0.2'     b'Iris-setosa'        small
3    b'4.6'  b'3.1'  1.5  b'0.2'     b'Iris-setosa'        small
4    b'5.0'  b'3.6'  1.4  b'0.2'     b'Iris-setosa'        small
..      ...     ...  ...     ...                ...          ...
145  b'6.7'  b'3.0'  5.2  b'2.3'  b'Iris-virginica'        large
146  b'6.3'  b'2.5'  5.0  b'1.9'  b'Iris-virginica'        large
147  b'6.5'  b'3.0'  5.2  b'2.0'  b'Iris-virginica'        large
148  b'6.2'  b'3.4'  5.4  b'2.3'  b'Iris-virginica'        large
149  b'5.9'  b'3.0'  5.1  b'1.8'  b'Iris-virginica'        large

[150 rows x 6 columns]


Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [146]:
most_frequent = dataFrame[2].mode()
print(most_frequent)

0    1.5
Name: 2, dtype: float64
