Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [143]:
import numpy as np

In [144]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
list1 = [1,2,3,4,5]

arr1 = np.array(list1)
print(arr1)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
list2 = [[1,2,3], [4,5,6]]

arr2 = np.array(list2)
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [145]:
# Write a NumPy function to create an array with random values of shape [3,4]
a1 = np.random.rand(3,4)
# print(a1)

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
a2 = np.zeros((3,4))
# print(a2)

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
a3 = np.ones((3,4))
# print(a3)

In [146]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
arr = np.linspace(1, 10, 19)             #(start, stop, step)
# print(arr)

### Basic array operations
- algebraic operations
- logical operations

In [147]:
a = np.array([[-4,6, 8], 
              [9, 3, 1], 
              [1, 8, 5]])
b = np.array([[11, 16, 18], 
              [90, 37, 81], 
              [61, 48, 75]])

In [148]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
np.add(a,b)
np.subtract(a,b)
np.multiply(a,b)
np.divide(a,b)

array([[-0.36363636,  0.375     ,  0.44444444],
       [ 0.1       ,  0.08108108,  0.01234568],
       [ 0.01639344,  0.16666667,  0.06666667]])

In [149]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
np.sum(a, axis=0)
# Write a NumPy function to get the sum of the array 'a' along axis=1
np.sum(a, axis=1)

array([10, 13, 14])

In [150]:
# Write a NumPy function to reverse the array 'a'
rev_a1 = np.flip(a)
# print(rev_a1)

# Write a NumPy function to reverse the array 'a' along axis=0
rev_a2 = np.flip(a, axis=0)
# print(rev_a2)

# Write a NumPy function to reverse the array 'a' along axis=1
rev_a3 = np.flip(a ,axis=1)
# print(rev_a3)


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [151]:
a = np.array([[-4,6,8], 
              [9, 3, 1], 
              [1, 8, 5]])
b = np.array([[11,16,18], 
              [90, 37, 81], 
              [61, 48, 75]])

In [152]:
# Write a NumPy function to sort the array 'a'
np.sort(a)
# Write a NumPy function to sort the array 'a' along axis=0
np.sort(a ,axis=0)
# Write a NumPy function to sort the array 'a' along axis=1
np.sort(a ,axis=1)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
np.sort(a[::-1], axis=0)

array([[-4,  3,  1],
       [ 1,  6,  5],
       [ 9,  8,  8]])

In [153]:
# Write a NumPy function to argsort the array along axis=0
np.argsort(a, axis=0)
# Write a NumPy function to argsort the array along axis=1
np.argsort(a, axis=1)

array([[0, 1, 2],
       [2, 1, 0],
       [0, 2, 1]], dtype=int64)

In [154]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
np.concatenate((a,b))
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
np.concatenate((a,b), axis=0)
# Note: You can do the same function using stacking, discover and try that :)
np.stack((a,b), axis=0)

array([[[-4,  6,  8],
        [ 9,  3,  1],
        [ 1,  8,  5]],

       [[11, 16, 18],
        [90, 37, 81],
        [61, 48, 75]]])

### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [155]:
a = np.array([[4,6,8], 
              [9, 3, 1], 
              [1, 8, 5]])

In [156]:
# Write a NumPy function to get the Number of dimensions
np.ndim(a)
# Write a NumPy function to get the Shape of the array
np.shape(a)
# Write a NumPy function to get the Size of the array
np.size(a)

9

In [157]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
a = np.reshape(a ,(1,9))      # (a, 9) gives a 1d array of same elements
# print(a)

In [158]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
a = a[np.newaxis]
# print(a)
a = np.expand_dims(a ,axis=0)
# print(a)

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [159]:
a = np.array([[4,6,0], 
              [0, 3, 1], 
              [1, 8, 5]])

In [160]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range

print(a[2, :2])    #indexing and slicing using int
print(a[(1,1)])    #indexing using tuple (cannot slice in tuple as they are immutable)

for i in range(len(a)):
    print(a[0,i])  #using range


[1 8]
3
4
6
0


In [161]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
print(a[a>4])
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
print(a[(a>4) & (a%2==0)])

[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [162]:
a = np.array([[4,6,0], 
              [0, 3, 1], 
              [1, 8, 5]])

In [163]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
b = np.copy(a)        # b = 1 also copies the array
print(b+1)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [164]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [165]:
import pandas as pd

# Write a Pandas function to drop rows that contain a missing value.
df = pd.DataFrame(iris_2d)       

df.isnull().sum()   # to check if any row has null entries 
df = df.dropna()
# df.head()

In [166]:
# Write a Pandas function to find the correlation between the first two columns.
df[0].corr(df[1])


-0.1093692499506493

In [167]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
df[2].mean()
df[2].median()
df[2].std()

1.7644204199522626

In [168]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
df['Volume'] = 3.14*df[2]*df[0]*df[0]/3
# df.head()


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [169]:
arr = np.ones(4, dtype=np.int64)
# print(arr)

Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [170]:
x = [1,2,3,4,5,6,7,8,9]

a = x[:4]
# print(a)
b = x[4:6]
# print(b)
c = x[6:9]
# print(c)

Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [171]:
x = np.random.randint(0,10 ,size=(2,5))
# print(x)
# [1] is done to select the second axis i.e. row.
x[1].max()     #value
x[1].argmax()  #index
x[1].min()
x[1].argmin()


3

### Pandas

Run the following load command and solve the following questions

In [172]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [173]:
data_frame = pd.DataFrame(iris)
# data_frame.head()

data_frame[4].nunique()

3

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [174]:
data_frame[2] = np.where((df[2] < 3.0), 'small', data_frame[2])                # works somewhat like if else
data_frame[2] = np.where((df[2] >= 3.0) & (df[2] < 5.0), 'medium', data_frame[2])
data_frame[2] = np.where((df[2] >= 5.0), 'large', data_frame[2])

# data_frame[2].value_counts()

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [175]:
data_frame[2].mode()

0    medium
Name: 2, dtype: object