Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [ ]:
import numpy as np

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
ar1=np.array([1,2,3,4,5])
print(ar1)
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
ar2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]

ar3=np.random.rand(3,4)
print(ar3)
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
ar4=np.zeros((3,4))
print(ar4)
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
ar5=np.ones((3,4))
print(ar5)



[[0.03795251 0.20944163 0.85332704 0.74963543]
 [0.77234034 0.90444451 0.08013244 0.56294164]
 [0.77303242 0.42680792 0.84478576 0.09957812]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
ar5=np.linspace(1,10,8)
print(ar5)
# Hint : Use np.arange or np.linspace

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]


### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
addition=np.add(a,b)
subtraction=np.subtract(a,b)
multiplication=np.multiply(a,b)
division=np.divide(a,b)
print(f"addition={addition}\nsubtration={subtraction}\nmultiplication={multiplication}\ndivision={division}\n")


addition=[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
subtration=[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
multiplication=[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
division=[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]



In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
ar6=np.sum(a,axis=0)
print(ar6)

# Write a NumPy function to get the sum of the array 'a' along axis=1
ar7=np.sum(a,axis=1)
print(ar7)


[ 6 17 14]
[10 13 14]


In [ ]:
# Write a NumPy function to reverse the array 'a'
ar8=np.flip(a)
print(ar8)

# Write a NumPy function to reverse the array 'a' along axis=0
ar9=np.flip(a,axis=0)
print(ar9)

# Write a NumPy function to reverse the array 'a' along axis=1
ar10=np.flip(a,axis=1)
print(ar10)


[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'
sorted_a=np.sort(a,axis=None).reshape(3,3)
print(sorted_a)

# Write a NumPy function to sort the array 'a' along axis=0
sorted_a_1=np.sort(a,axis=0)
print(sorted_a_1)
# Write a NumPy function to sort the array 'a' along axis=1
sorted_a_2=np.sort(a,axis=1)
print(sorted_a_2)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
sorted_a_1_des=np.flip(np.sort(a,axis=0),axis=0)
print(sorted_a_1_des)

[[-4  1  1]
 [ 3  5  6]
 [ 8  8  9]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [ ]:
# Write a NumPy function to argsort the array along axis=0
print(a.argsort(axis=0))

# Write a NumPy function to argsort the array along axis=1
print(a.argsort(axis=1))

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
print(np.concatenate((a,b)))
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
print(np.concatenate((a,b),axis=0))
# Note: You can do the same function using stacking, discover and try that :)
print(np.vstack((a,b)))

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
print(f"Size of a: {a.size}")

# Write a NumPy function to get the Shape of the array
print(f"Shape of a: {a.shape}")
# Write a NumPy function to get the Size of the array
print(f"No. of dimensions of a: {a.ndim}")

Size of a: 9
Shape of a: (3, 3)
No. of dimensions of a: 2


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
reshaped_array_a=np.reshape(a,(1,9))
print(reshaped_array_a)

[[4 6 8 9 3 1 1 8 5]]


In [ ]:
# Write a NumPy function to add a new axis to the array 'a'
# Method 1
print(a[:,np.newaxis])
# Method2
print(a[np.newaxis,:])
# Note : Show atleast two different ways of doing this


[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]
[[[4 6 8]
  [9 3 1]
  [1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [44]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
#indexing by integer
print(a[1])
#indexing by tuple
print(a[(1,2)])
#indexing by range
print(a[2,0:2])


[0 3 1]
1
[1 8]


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
print(np.where(a>4))

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
print(np.where((a>4) & (a%2==0)))

(array([0, 2, 2]), array([1, 1, 2]))
(array([0, 2]), array([1, 1]))


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
a_copy=np.copy(a)
a111=np.ones(a.shape)
a_final = a_copy + a111
print(a_final)


[[5. 7. 1.]
 [1. 4. 2.]
 [2. 9. 6.]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd
df=pd.DataFrame(iris_2d)
df_missremove=df.dropna(axis=0,inplace=True)


In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
print(df[0].corr(df[1]))

-0.10936924995064937


In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
mean=df[3].mean()
median=df[3].median()
std_dev=df[3].std()
print(f'Mean={mean}\nMedian={median}\nStandard Deviation={std_dev}')

Mean=1.1986666666666668
Median=1.3
Standard Deviation=0.7631607417008411


In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
vol = (np.pi * df[2] * df[0] ** 2) / 3
df['Volume'] = vol
print(df)



       0    1    2    3      Volume
0    5.1  3.5  1.4  0.2   38.132652
1    4.9  3.0  1.4  0.2   35.200498
2    4.7  3.2  1.3  0.2   30.072372
3    4.6  3.1  1.5  0.2   33.238050
4    5.0  3.6  1.4  0.2   36.651914
..   ...  ...  ...  ...         ...
145  6.7  3.0  5.2  2.3  244.445230
146  6.3  2.5  5.0  1.9  207.816354
147  6.5  3.0  5.2  2.0  230.069302
148  6.2  3.4  5.4  2.3  217.373079
149  5.9  3.0  5.1  1.8  185.910028

[150 rows x 5 columns]


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
x=np.arange(4,dtype=np.int64)
arr1=np.ones(x.shape)
print(arr1)

[1. 1. 1. 1.]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x=np.arange(10)
x_req=np.split(x,[4,6])
print(x_req)

[array([0, 1, 2, 3]), array([4, 5]), array([6, 7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
x = np.random.randint(0, 10, size=(2, 5))
print(x)
max_val = np.max(x, axis=1)
min_val = np.min(x, axis=1)
max_ind = np.argmax(x, axis=1)
min_ind = np.argmin(x, axis=1)
print(f"maximum value along the second axis={max_val}\nminimum value along the second axis={min_val}\nIndex ofmaximum value along the second axis={max_ind}\nIndex ofminimum value along the second axis={min_val}\n")

[[5 8 0 8 5]
 [6 8 6 3 8]]
maximum value along the second axis=[8 8]
minimum value along the second axis=[0 3]
Index ofmaximum value along the second axis=[1 1]
Index ofminimum value along the second axis=[0 3]



### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [ ]:
df = pd.DataFrame(iris, columns=names)

usc = df['species'].nunique()
print(usc)


3


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:
bins = [0, 3, 5, float('inf')]
labels = ['small', 'medium', 'large']
req_bins = pd.cut(df.iloc[:, 2].astype(float), bins=bins, labels=labels)
print(req_bins)

0       small
1       small
2       small
3       small
4       small
        ...  
145     large
146    medium
147     large
148     large
149     large
Name: petallength, Length: 150, dtype: category
Categories (3, object): ['small' < 'medium' < 'large']


Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
print((df.iloc[:, 2]).mode())

0    b'1.5'
Name: petallength, dtype: object
