Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [ ]:
import numpy as np

In [ ]:
import numpy as np
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
X = np.array([1,2,3,4,5])
print(X)
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(Y)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:

# Write a NumPy function to create an array with random values of shape [3,4]
X = np. random. randint(0, 3, 4)
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
Y = np.zeros(3,4)
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
Z = np.ones(3,4)

In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
def create_evenly_spaced_array(start, stop, num_intervals):
    return np.linspace(start, stop, num_intervals)

# Hint : Use np.arange or np.linspace

### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
def perform_operations(a, b):
    addition_result = np.add(a, b)
    subtraction_result = np.subtract(a, b)
    multiplication_result = np.multiply(a, b)
    division_result = np.divide(a, b)

    return addition_result, subtraction_result, multiplication_result, division_result

In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
def sum_along_axis_0(a):
    return np.sum(a, axis=0)
# Write a NumPy function to get the sum of the array 'a' along axis=1
def sum_along_axis_0(a):
    return np.sum(a, axis=1)

In [ ]:
# Write a NumPy function to reverse the array 'a'
def reverse_array(a):
    return a[::-1]
# Write a NumPy function to reverse the array 'a' along axis=0
def reverse_array_along_axis_0(a):
    return np.flip(a, axis=0)
# Write a NumPy function to reverse the array 'a' along axis=1
def reverse_array_along_axis_1(a):
    return np.flip(a, axis=1)

### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'
def sort_array(a):
    return np.sort(a)
# Write a NumPy function to sort the array 'a' along axis=0
def sort_array(a):
    return np.sort(a, axis=0)
# Write a NumPy function to sort the array 'a' along axis=1
def sort_array(a):
    return np.sort(a, axis=1)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
def sort_array_descending(a):
    sorted_array = np.sort(a, axis=0)
    return np.flip(sorted_array, axis=0)

In [ ]:
# Write a NumPy function to argsort the array along axis=0
def argsort_array_along_axis_0(a):
    return np.argsort(a, axis=0)
# Write a NumPy function to argsort the array along axis=1
def argsort_array_along_axis_1(a):
    return np.argsort(a, axis=1)

In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
def concatenate_arrays(a, b, axis=0):
    return np.concatenate(a, b)
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
def concatenate_arrays(a, b):
    return np.concatenate((a, b), axis=0)
# Note: You can do the same function using stacking, discover and try that :)


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
def get_num_dimensions(array):
    return array.ndim
# Write a NumPy function to get the Shape of the array
def get_array_shape(array):
    return array.shape
# Write a NumPy function to get the Size of the array
def get_array_size(arr):
    return arr.size

In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
def reshape_array(a):
    return np.reshape(a, (1, 9))

In [ ]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
def add_new_axis_method1(a):
    return a[np.newaxis, :]

def add_new_axis_method2(a):
    return np.reshape(a, (1, *a.shape))

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
def numpy_indexing(array):
    # Indexing by an integer
    print("Indexing by an integer:")
    print(array[2])

    # Indexing by a tuple
    print("\nIndexing by a tuple:")
    print(array[1, 2])

    # Using range
    print("\nUsing range:")
    print(array[:, 1:3])

In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
def select_values_greater_than_4(array):
    condition = array > 4
    selected_values = array[condition]
    return selected_values
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
def select_values_satisfying_conditions(array):
    condition = (array > 4) & (array % 2 == 0)
    selected_values = array[condition]
    return selected_values

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
def increase_array_elements_by_1(a):
    copied_array = np.copy(a)
    copied_array += 1

    return copied_array

## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [6]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value.
def drop_rows_with_missing_values(df):
    cleaned_df = df.dropna()
    return cleaned_df

In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
def find_correlation_first_two_columns(df):
    correlation = df.iloc[:, 0].corr(df.iloc[:, 1])
    return correlation

In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
def calculate_stats_column_3(df):
    mean = df.iloc[:, 2].mean()
    median = df.iloc[:, 2].median()
    std_dev = df.iloc[:, 2].std()
    return mean, median, std_dev

In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
def calculate_volume(df):
    pi = np.pi
    sepal_length = df[:, 0]
    petal_length = df[:, 2]
    volume = (pi * petal_length * sepal_length ** 2) / 3
    return volume

def add_volume_column(df):
    volume = calculate_volume(df.values)
    df['volume'] = volume

    return df

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
import numpy as np

x = np.arange(4, dtype=np.int64)
ones = np.ones_like(x)

print(ones)


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
import numpy as np
x = np.arange(1, 10)
x1, x2, x3 = np.split(x, [4, 6])

print(x1, x2, x3)


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
x = np.random.rand(2, 5) * 10
max = np.argmax(x, axis=1)
min = np.argmin(x, axis=1)
print(max,min)
print(x)

### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [ ]:
def count_unique_species(df):
    return df['species'].value_counts()

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [7]:

def classify_petal_length(petal_length):
    petal_length_str = str(petal_length.decode('utf-8'))  # Decode bytes to string
    petal_length_float = float(petal_length_str)  # Convert string to float
    if petal_length_float < 3:
        return 'small'
    elif petal_length_float < 5:
        return 'medium'
    else:
        return 'large'

text_array = df.iloc[:, 2].apply(classify)

print(text_array)

NameError: name 'df' is not defined

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
df['petallength'].value_counts()