Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [1]:
import numpy as np

In [2]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
arr1 = np.array([1,2,3,4,5])
print(arr1)
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# Write a NumPy function to create an array with random values of shape [3,4]
arr3=np.random.rand(3,4)
print(arr3)

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
arr4=np.zeros((3,4),dtype='int')
print(arr4)

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
arr5=np.ones((3,4),dtype='int')
print(arr5)


[[0.91732731 0.96351439 0.8600372  0.4100282 ]
 [0.65736943 0.65164193 0.28013686 0.45295603]
 [0.47261491 0.7450317  0.14650734 0.44252881]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [4]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace

arr6=np.linspace(1,9,5,dtype=int)
#arr6=np.arange(1,10,2)
print(arr6)

[1 3 5 7 9]


### Basic array operations
- algebraic operations
- logical operations

In [5]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [6]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
np.add(a,b)
np.subtract(a,b)
np.multiply(a,b)
np.divide(a,b)


array([[-0.36363636,  0.375     ,  0.44444444],
       [ 0.1       ,  0.08108108,  0.01234568],
       [ 0.01639344,  0.16666667,  0.06666667]])

In [7]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
np.sum(a,axis=0)
# Write a NumPy function to get the sum of the array 'a' along axis=1
np.sum(a,axis=1)


array([10, 13, 14])

In [8]:
# Write a NumPy function to reverse the array 'a'
np.flip(a)

# Write a NumPy function to reverse the array 'a' along axis=0
np.flip(a, axis=0)

# Write a NumPy function to reverse the array 'a' along axis=1
np.flip(a, axis=1)


array([[ 8,  6, -4],
       [ 1,  3,  9],
       [ 5,  8,  1]])

### Sorting and concatenation
- sort arrays
- join multiple arrays


In [9]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [10]:
# Write a NumPy function to sort the array 'a'
np.sort(a)

# Write a NumPy function to sort the array 'a' along axis=0
np.sort(a, axis=0)

# Write a NumPy function to sort the array 'a' along axis=1
np.sort(a, axis=1)

# Write a NumPy function to sort the array 'a' in descending order along axis=0
np.sort(a, axis=0)[::-1]

array([[ 9,  8,  8],
       [ 1,  6,  5],
       [-4,  3,  1]])

In [11]:
# Write a NumPy function to argsort the array along axis=0
np.argsort(a, axis=0)

# Write a NumPy function to argsort the array along axis=1
np.argsort(a, axis=1)

array([[0, 1, 2],
       [2, 1, 0],
       [0, 2, 1]])

In [12]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
np.concatenate((a,b))

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
np.concatenate((a,b), axis=0)

# Note: You can do the same function using stacking, discover and try that :)
# print(np.stack((a, b), axis=0))

array([[-4,  6,  8],
       [ 9,  3,  1],
       [ 1,  8,  5],
       [11, 16, 18],
       [90, 37, 81],
       [61, 48, 75]])

### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [13]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [14]:
# Write a NumPy function to get the Number of dimensions
print(a.ndim)

# Write a NumPy function to get the Shape of the array
print(np.shape(a))

# Write a NumPy function to get the Size of the array
print(np.size(a))


2
(3, 3)
9


In [15]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
a.reshape(1,9)


array([[4, 6, 8, 9, 3, 1, 1, 8, 5]])

In [16]:
# Write a NumPy function to add a new axis to the array 'a'
print(a[:, np.newaxis])

print(np.expand_dims(a, axis=1))
# Note : Show atleast two different ways of doing this


[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]
[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [17]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [18]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
a[1,0]
a[0:2,1:]

# Show all three - indexing by a integer, indexing by a tuple, using range
a[2,1]

a[(2,1)]

a[1:,0:2]


array([[0, 3],
       [1, 8]])

In [19]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
a[np.where(a>4)]

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
a[np.where((a>4) & (a%2==0))]

array([6, 8])

### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [20]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [21]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
x = np.copy(a)

a = a+1
print(a)
print(x)


[[5 7 1]
 [1 4 2]
 [2 9 6]]
[[4 6 0]
 [0 3 1]
 [1 8 5]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [22]:
import pandas as pd

In [23]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [24]:
# Write a Pandas function to drop rows that contain a missing value.
iris_df = pd.read_csv(url, names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species'])
cleaned_iris = iris_df.dropna()

print(cleaned_iris)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [25]:
# Write a Pandas function to find the correlation between the first two columns.
print(cleaned_iris['sepal_length'].corr(cleaned_iris['sepal_width']))

-0.10936924995064937


In [26]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
print(cleaned_iris.iloc[:, 2].mean())
print(cleaned_iris.iloc[:, 2].median())
print(cleaned_iris.iloc[:, 2].std())

3.758666666666666
4.35
1.7644204199522626


In [27]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petal_length x sepal_length^2)/3

volume = (3.14*iris_df['petal_length']*(iris_df['sepal_length'])**2)/3
iris_df['volume'] = volume

print(iris_df)
print(np.column_stack((iris_df,volume)))

# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

     sepal_length  sepal_width  petal_length  petal_width         species  \
0             5.1          3.5           1.4          0.2     Iris-setosa   
1             4.9          3.0           1.4          0.2     Iris-setosa   
2             4.7          3.2           1.3          0.2     Iris-setosa   
3             4.6          3.1           1.5          0.2     Iris-setosa   
4             5.0          3.6           1.4          0.2     Iris-setosa   
..            ...          ...           ...          ...             ...   
145           6.7          3.0           5.2          2.3  Iris-virginica   
146           6.3          2.5           5.0          1.9  Iris-virginica   
147           6.5          3.0           5.2          2.0  Iris-virginica   
148           6.2          3.4           5.4          2.3  Iris-virginica   
149           5.9          3.0           5.1          1.8  Iris-virginica   

         volume  
0     38.113320  
1     35.182653  
2     30.057127  
3  

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [28]:
x = np.arange(4, dtype=np.int64)
print(x)

y = np.ones(4, dtype=np.int64)
print(y)

z = np.ones_like(x)
print(z)

[0 1 2 3]
[1 1 1 1]
[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [29]:
x = np.arange(1,10)
print(x)

np.array_split(x,[4,6])
#as we have to split the array x at the indices 4,6.

[1 2 3 4 5 6 7 8 9]


[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]

Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [30]:
x = np.random.uniform(0,10, size = (2,5))
print(x)

print(np.amax(x, axis=1))
print(np.argmax(x, axis=1))

print(np.amin(x, axis=1))
print(np.argmin(x, axis=1))


[[9.34843987 2.00176636 9.87712908 1.16522313 0.98728326]
 [5.05056308 3.48402382 0.66207671 1.5064005  6.59907915]]
[9.87712908 6.59907915]
[2 4]
[0.98728326 0.66207671]
[4 2]


### Pandas

Run the following load command and solve the following questions

In [31]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [32]:
iris_df = pd.read_csv(url, names = ['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'])
print(iris_df['species'].nunique())

3


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [33]:
print(pd.cut(iris_df['petallength'], bins=[0,3,5,9999], labels=['small','medium','large']))

0       small
1       small
2       small
3       small
4       small
        ...  
145     large
146    medium
147     large
148     large
149     large
Name: petallength, Length: 150, dtype: category
Categories (3, object): ['small' < 'medium' < 'large']


Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [34]:
print(iris_df.iloc[:, 2].mode())

0    1.5
Name: petallength, dtype: float64
