<a href="https://colab.research.google.com/github/shrutisekhar02/Cycle_GANS_project/blob/main/CYCLE_GANS_Assignment1_230723.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [1]:
import numpy as np

In [2]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
list1=[1,2,3,4,5]
a=np.array(list1)
print(a)
print(a.ndim)
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
list2=[[1,2,3],[3,4,5],[4,5,6]]
b=np.array(list2)
print(b)
print(b.ndim)

[1 2 3 4 5]
1
[[1 2 3]
 [3 4 5]
 [4 5 6]]
2


In [3]:
# Write a NumPy function to create an array with random values of shape [3,4]
a=np.random.randn(3,4)
print(a)
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
a=np.zeros([3,4])
print(a)

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
a=np.ones([3,4])
print(a)

[[-0.3124983  -1.9060346  -0.39870975  1.1753493 ]
 [ 1.08933542  0.36196163  1.16957728  0.84432188]
 [-1.88385181 -0.52430057  1.04502447 -0.8006374 ]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
a=np.arange(0,100,20)
print(a)
# Hint : Use np.arange or np.linspace

[ 0 20 40 60 80]


### Basic array operations
- algebraic operations
- logical operations

In [5]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [6]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
add=np.add(a,b)
sub=np.subtract(a,b)
mul=np.multiply(a,b)
div=np.divide(a,b)
print(add,"\n\n",sub,"\n\n",mul,"\n\n",div)

[[ 7 22 26]
 [99 40 82]
 [62 56 80]] 

 [[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]] 

 [[-44  96 144]
 [810 111  81]
 [ 61 384 375]] 

 [[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [7]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
axis0=np.sum(a,axis=0)
print(axis0)

# Write a NumPy function to get the sum of the array 'a' along axis=1
axis1=np.sum(a,axis=1)
print(axis1)


[ 6 17 14]
[10 13 14]


In [8]:
# Write a NumPy function to reverse the array 'a'
reverse=np.flip(a)
print(reverse)

# Write a NumPy function to reverse the array 'a' along axis=0
revaxis0=np.flip(a,axis=0)
print(revaxis0)

# Write a NumPy function to reverse the array 'a' along axis=1
revaxis1=np.flip(a,axis=1)
print(revaxis1)


[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [9]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [10]:
# Write a NumPy function to sort the array 'a'
sort=np.sort(a)
print(sort)
# Write a NumPy function to sort the array 'a' along axis=0
sort0=np.sort(a,axis=0)
print(sort0)
# Write a NumPy function to sort the array 'a' along axis=1
sort1=np.sort(a,axis=1)
print(sort1)

# Write a NumPy function to sort the array 'a' in descending order along axis=0
sortdesc=-np.sort(-a,axis=0)
print(sortdesc)


[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [11]:
# Write a NumPy function to argsort the array along axis=0
axis0=np.argsort(a,axis=0)
print(axis0)

# Write a NumPy function to argsort the array along axis=1
axis1=np.argsort(a,axis=1)
print(axis1)

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [12]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
conc=np.concatenate((a,b),axis=None)
print(conc)

# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0

conc0=np.concatenate((a,b),axis=0)
print(conc0)
# Note: You can do the same function using stacking, discover and try that :)
stack=np.vstack((a,b))
print(stack)


[-4  6  8  9  3  1  1  8  5 11 16 18 90 37 81 61 48 75]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [13]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [14]:
# Write a NumPy function to get the Number of dimensions
dim=np.ndim(a)
print(dim)

# Write a NumPy function to get the Shape of the array
shape=np.shape(a)
print(shape)

# Write a NumPy function to get the Size of the array
size=np.size(a)
print(size)


2
(3, 3)
9


In [15]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
b=a.reshape((1,9))
print(b)

[[4 6 8 9 3 1 1 8 5]]


In [16]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
b=np.expand_dims(a,axis=0)
print(b)
print(np.shape(b))
print("\n\n")
b=a.reshape((1,)+a.shape)
print(b)
print(np.shape(b))

[[[4 6 8]
  [9 3 1]
  [1 8 5]]]
(1, 3, 3)



[[[4 6 8]
  [9 3 1]
  [1 8 5]]]
(1, 3, 3)


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [17]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [18]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
print(a[2])
print(a[(1,2)])
print(a[2,0:2])

[1 8 5]
1
[1 8]


In [19]:

# Write a NumPy function to select values satisfying a specific condition like Values greater than 4

print(a[a>4])#boolean indexing

# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
print(a[(a>4)&(a%2==0)])


[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [20]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [21]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
b=a.copy()
b=b+1
print(a)
print(b)


[[4 6 0]
 [0 3 1]
 [1 8 5]]
[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [22]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [24]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd
iris_2d=pd.DataFrame(iris_2d)
print(iris_2d.info())
#150 non null entries in all 4 columns implies no null values

iris_2d.dropna(inplace=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       150 non-null    float64
 1   1       150 non-null    float64
 2   2       150 non-null    float64
 3   3       150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB
None


In [25]:
# Write a Pandas function to find the correlation between the first two columns.
iris_2d[0].corr(iris_2d[1])

-0.10936924995064937

In [26]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
mean=iris_2d[2].mean()
print(mean)
median=iris_2d[2].median()
print(median)
mode=iris_2d[2].mode()
print(mode)

3.758666666666666
4.35
0    1.5
Name: 2, dtype: float64


In [27]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
import math
vol=(math.pi*iris_2d[2]*(iris_2d[0])**2)/3
iris_2d["vol"]=vol
print(iris_2d)

       0    1    2    3         vol
0    5.1  3.5  1.4  0.2   38.132652
1    4.9  3.0  1.4  0.2   35.200498
2    4.7  3.2  1.3  0.2   30.072372
3    4.6  3.1  1.5  0.2   33.238050
4    5.0  3.6  1.4  0.2   36.651914
..   ...  ...  ...  ...         ...
145  6.7  3.0  5.2  2.3  244.445230
146  6.3  2.5  5.0  1.9  207.816354
147  6.5  3.0  5.2  2.0  230.069302
148  6.2  3.4  5.4  2.3  217.373079
149  5.9  3.0  5.1  1.8  185.910028

[150 rows x 5 columns]


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [28]:
x=np.arange(4,dtype=np.int64)

onearray=np.ones_like(x)
print(onearray)
print(onearray.shape,onearray.dtype)

[1 1 1 1]
(4,) int64


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [29]:
x=np.arange(1,10)
print(np.split(x,[4,6]))


[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [30]:
y=np.random.randint(0,10,size=10)
x=y.reshape(2,5)
print("max val:",np.max(x,axis=1)," index:",np.argmax(x,axis=1),"\n","min val:",np.min(x,axis=1)," index:",np.argmin(x,axis=1))

max val: [9 9]  index: [2 2] 
 min val: [0 0]  index: [0 3]


### Pandas

Run the following load command and solve the following questions

In [31]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [32]:
iris=pd.DataFrame(iris,columns=names)

iris['species'].nunique()


3

Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [33]:


#all values are in binary
iris['petallength'] = iris['petallength'].astype(float)

petal_len=pd.cut(iris['petallength'],bins=[0,3,5,float('inf')],labels=['small','medium','large'])
print(petal_len)

0       small
1       small
2       small
3       small
4       small
        ...  
145     large
146    medium
147     large
148     large
149     large
Name: petallength, Length: 150, dtype: category
Categories (3, object): ['small' < 'medium' < 'large']


Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [34]:
print(iris['petallength'].mode()[0])

1.5
