Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [ ]:
import numpy as np

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
list=[1,2,3,4,5]
arr1=np.array(list)
print(arr1)

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]
arr3=np.random.random((3,4))
print(arr3)
print()
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
arr4=np.zeros((3,4))
print(arr4)
print()
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
arr5=np.ones((3,4),dtype='int')
print(arr5)

[[0.22286432 0.87591155 0.52546607 0.62539675]
 [0.50587452 0.48672606 0.24115505 0.40268155]
 [0.59535239 0.81949472 0.83824831 0.52922817]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
arr6=np.arange(0,11,2)
print(arr6)

[ 0  2  4  6  8 10]


### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
sum=np.add(a,b) #add
dif=np.subtract(a,b) #subtract
product=np.multiply(a,b) #multiply
quot=np.divide(a,b) #divide

In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
c=np.sum(a, axis=0)

# Write a NumPy function to get the sum of the array 'a' along axis=1
d=np.sum(a, axis=1)

In [ ]:
# Write a NumPy function to reverse the array 'a'
rev=np.flip(a)

# Write a NumPy function to reverse the array 'a' along axis=0
rev0=np.flip(a,axis=0)

# Write a NumPy function to reverse the array 'a' along axis=1
rev1=np.flip(a,axis=1)


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'
sort=np.sort(a)

# Write a NumPy function to sort the array 'a' along axis=0
sort0=np.sort(a,axis=0)
# Write a NumPy function to sort the array 'a' along axis=1
sort1=np.sort(a,axis=1)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
sort_d=np.flip(sort0,axis=0)#sort_d=np.sort(a,axis=0)[::-1]


In [ ]:
# Write a NumPy function to argsort the array along axis=0
arg0=np.argsort(a,axis=0)
print(arg0)
print()
# Write a NumPy function to argsort the array along axis=1
arg1=np.argsort(a,axis=1)
print(arg1)

[[0 1 1]
 [2 0 2]
 [1 2 0]]

[[0 1 2]
 [2 1 0]
 [0 2 1]]


In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
con=np.concatenate((a,b))
print(con)
print()
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
con0=np.concatenate((a,b),axis=0)
print(con0)
# Note: You can do the same function using stacking, discover and try that :)


[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]

[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
dim=np.ndim(a)
print(dim)
# Write a NumPy function to get the Shape of the array
shape=np.shape(a)
print(shape)
# Write a NumPy function to get the Size of the array
size=np.size(a)
print(size)

2
(3, 3)
9


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
rs=np.reshape(a,(1,9))
print(rs)

[[4 6 8 9 3 1 1 8 5]]


In [ ]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
#method1
new_axis1=np.reshape(a,(3,3,1))
print(new_axis1)
#method2
new_axis2=np.expand_dims(a, axis=1)
print(new_axis2)

[[[4]
  [6]
  [8]]

 [[9]
  [3]
  [1]]

 [[1]
  [8]
  [5]]]
[[[4 6 8]]

 [[9 3 1]]

 [[1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
print(a[2:3, 1:3])
print()
# Show all three - indexing by a integer, indexing by a tuple, using range
#indexing by int
print(a[2][1])
print()
#by tuple
t1=(0,1)
t2=(1,2)
print(a[t1,t2])
print()
# by range
for i in range(len(a)):
  if(i<2):
    print(a[i])

[[8 5]]

8

[6 1]

[4 6 0]
[0 3 1]


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
selected=a[a>4]
print(selected)
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
selected2=a[(a>4) & (a%2==0)]
print(selected2)

[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
b=np.copy(a)
c=np.copy(a+1)
print(c)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [ ]:
import pandas as pd
iris_2d=pd.DataFrame(iris_2d)
iris_2d

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value.
iris_2d.dropna()

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
x=iris_2d[0].corr(iris_2d[1])
x

-0.10936924995064937

In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
mean=iris_2d[2].mean()
median = iris_2d[2].median()
mode = iris_2d[2].mode()
mean = iris_2d[2].mean()

In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
vol=[]
for i in iris_2d.index:
  v=(3.14*(iris_2d[2][i])*((iris_2d[0][i])**2))/3
  vol.append(v)
iris_2d['volume']=vol
iris_2d


0    1    2    3      volume
0    5.1  3.5  1.4  0.2   38.113320
1    4.9  3.0  1.4  0.2   35.182653
2    4.7  3.2  1.3  0.2   30.057127
3    4.6  3.1  1.5  0.2   33.221200
4    5.0  3.6  1.4  0.2   36.633333
..   ...  ...  ...  ...         ...
145  6.7  3.0  5.2  2.3  244.321307
146  6.3  2.5  5.0  1.9  207.711000
147  6.5  3.0  5.2  2.0  229.952667
148  6.2  3.4  5.4  2.3  217.262880
149  5.9  3.0  5.1  1.8  185.815780

[150 rows x 5 columns]

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
y=np.ones(4, dtype=np.int64)

Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x=np.array([1,2,3,4,5,6,7,8,9])
print(np.split(x,[4,6]))

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
x=np.random.uniform(0,10,size=[2,5])
a=np.max(x,axis=1)
b=np.min(x,axis=1)
a_index=np.argmax(x,axis=1)
b_index=np.argmin(x,axis=1)
print(a,a_index,b,b_index)

[6.20492571 7.83446298] [2 3] [1.54034254 2.19251733] [0 1]


### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [ ]:
import pandas as pd
data = {}
for i in range(5):
  data[names[i]] = iris[:, i]
df = pd.DataFrame(data)
df

sepallength sepalwidth petallength petalwidth            species
0        b'5.1'     b'3.5'      b'1.4'     b'0.2'     b'Iris-setosa'
1        b'4.9'     b'3.0'      b'1.4'     b'0.2'     b'Iris-setosa'
2        b'4.7'     b'3.2'      b'1.3'     b'0.2'     b'Iris-setosa'
3        b'4.6'     b'3.1'      b'1.5'     b'0.2'     b'Iris-setosa'
4        b'5.0'     b'3.6'      b'1.4'     b'0.2'     b'Iris-setosa'
..          ...        ...         ...        ...                ...
145      b'6.7'     b'3.0'      b'5.2'     b'2.3'  b'Iris-virginica'
146      b'6.3'     b'2.5'      b'5.0'     b'1.9'  b'Iris-virginica'
147      b'6.5'     b'3.0'      b'5.2'     b'2.0'  b'Iris-virginica'
148      b'6.2'     b'3.4'      b'5.4'     b'2.3'  b'Iris-virginica'
149      b'5.9'     b'3.0'      b'5.1'     b'1.8'  b'Iris-virginica'

[150 rows x 5 columns]

Q4 Write a Pandas function to find the count of unique species.

In [ ]:
x = df['species'].nunique()
x

3

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
txt=[]
for i in range(len(iris_2d)):
  if(iris_2d[i][2]<3):
    txt.append("small")
  elif(iris_2d[i][2]>=3 and iris_2d[i][2]<5):
    txt.append("medium")
  else:
    txt.append("large")

txt

['small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'large',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'medium',
 'mediu

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
y=df.mode()['petallength'][0]
y

b'1.5'