Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [3]:
import numpy as np

In [ ]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
import numpy as np
list=np.array([1,2,3,4,5])
for x in list:
  print(x)
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
from numpy import random
lst2=np.random.randint(100,size=(3,3))
print(lst2)

1
2
3
4
5
[[70 19 25]
 [56 80 72]
 [57 93 48]]


In [ ]:
# Write a NumPy function to create an array with random values of shape [3,4]
import numpy
from numpy import random

def fun1():
  arr = random.randint(100,size=(3,4))
  return arr
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
def fun2():
  arr2 = numpy.zeros((3,4))
  return arr2
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
def fun3():
  arr3=numpy.ones((3,4))
  return arr3

[0. 0. 0. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
import numpy as np
def funct(start,end,gap):
  arr=np.arange(start,end,gap)
  return arr
# Hint : Use np.arange or np.linspace

[1 3 5]


### Basic array operations
- algebraic operations
- logical operations

In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])
import numpy as np
def myadd(x,y):
  return x+y
def mysub(x,y):
  return x-y
def mymulti(x,y):
  return x*y
def mydiv(x,y):
  return x/y
myadd = np.frompyfunc(myadd, 2, 1)
mysub = np.frompyfunc(mysub, 2, 1)
mymulti = np.frompyfunc(mymulti, 2, 1)
mydiv = np.frompyfunc(mydiv, 2, 1)

[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]


In [ ]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
import numpy as np
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
def sum0(arr):
  return np.sum(arr,axis=0)
# Write a NumPy function to get the sum of the array 'a' along axis=1
def sum1(arr):
  return np.sum(a,axis=1)

[ 6 17 14]


In [ ]:
# Write a NumPy function to reverse the array 'a'
import numpy

a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
def rev(arr):
  return numpy.flip(a)
# Write a NumPy function to reverse the array 'a' along axis=0
def rev0(arr):
  return numpy.flip(a,axis=0)
# Write a NumPy function to reverse the array 'a' along axis=1
def rev1(arr):
  return numpy.flip(a,axis=1)

### Sorting and concatenation
- sort arrays
- join multiple arrays


In [ ]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [ ]:
# Write a NumPy function to sort the array 'a'
import numpy as np
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
def sortarr(arr):
  return np.sort(a)
# Write a NumPy function to sort the array 'a' along axis=0
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
def sortarr0(arr):
  return np.sort(a,axis=0)
# Write a NumPy function to sort the array 'a' along axis=1
def sortarr1(arr):
  return np.sort(a,axis=1)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
def sortdes(arr):
  x=np.sort(a,axis=0)
  return np.flip(x,axis=0)


[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [ ]:
# Write a NumPy function to argsort the array along axis=0
import numpy as np
arr=np.array([[1,5,6,7,2,3],[2,34,5,9,0,4]])
def myargsort0(arr):
  return np.argsort(arr,axis=0)
# Write a NumPy function to argsort the array along axis=1
def myargsort1(arr):
  return np.argsort(arr,axis=1)

[[0 0 1 0 1 0]
 [1 1 0 1 0 1]]
[[0 4 5 1 2 3]
 [5 2 4 1 0 3]]


In [ ]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
def myconcat(a,b):
  return np.concatenate((a, b))
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
def myconcat0(arr):
  return np.concatenate((a, b), axis=0)
# Note: You can do the same function using stacking, discover and try that :)


[[1 2]
 [3 4]
 [5 6]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [ ]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to get the Number of dimensions
import numpy as np
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])
def mydim(a):
  return np.ndim(a)
# Write a NumPy function to get the Shape of the array
def myshap(a):
  return np.shape(a)
# Write a NumPy function to get the Size of the array
def mysize(a):
  return np.size(a)

9


In [ ]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
import numpy as np
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])
def myreshap(a):
  return np.reshape(a,(1,9))

[[4 6 8 9 3 1 1 8 5]]


In [ ]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
import numpy as np
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])
def addaxis1(a):
  return a[np.newaxis]

def addaxis2(a):
  return np.expand_dims(a,0)

print(addaxis1(a))

[[[4 6 8]
  [9 3 1]
  [1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [4]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [8]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
print(a[1, 2:3])#indexing by slicing and integer
print(a[(1,2)])#indexing by using tuple
print(a[range(1,3),1])#indexing using range



[1]
1
[3 8]


In [ ]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
import numpy as np
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
def grt4(a):
  return a[a>4]
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
def grt4div2(a):
  return a[(a>4)&(a%2==0)]


[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [ ]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [ ]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
import numpy as np
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])
def mycpy(a):
  return np.copy(a)
a+=1
for c in a:
  for b in c:
    print(b,end=" ")
  print("\n")

5 7 1 

1 4 2 

2 9 6 



## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [ ]:
# Write a Pandas function to drop rows that contain a missing value.
import numpy as np

import pandas as pd
def drop_row(df):
  return df.dropna()

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]


In [ ]:
# Write a Pandas function to find the correlation between the first two columns.
import pandas as pd
def correl(df):
  return df[0].corr(df[1])

In [ ]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
import pandas as pd
def col_stats(df):
  stats = {
        "mean": df[2].mean(),
        "median": df[2].median(),
        "standard_deviation": df[2].std()
    }
  return stats

In [ ]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
import pandas as pd
import numpy as np
def addvol(df):
  vol=(df[2]*df[0]*df[0]*(np.pi))/3
  df[4]=vol
  return df
df=pd.DataFrame(iris_2d)
print(addvol(df))
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column

       0    1    2    3           4
0    5.1  3.5  1.4  0.2   38.132652
1    4.9  3.0  1.4  0.2   35.200498
2    4.7  3.2  1.3  0.2   30.072372
3    4.6  3.1  1.5  0.2   33.238050
4    5.0  3.6  1.4  0.2   36.651914
..   ...  ...  ...  ...         ...
145  6.7  3.0  5.2  2.3  244.445230
146  6.3  2.5  5.0  1.9  207.816354
147  6.5  3.0  5.2  2.0  230.069302
148  6.2  3.4  5.4  2.3  217.373079
149  5.9  3.0  5.1  1.8  185.910028

[150 rows x 5 columns]


# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
arr=np.ones((1,4),dtype=np.int64)

[[1 1 1 1]]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x=[1,2,3,4,5,6,7,8,9]
a1=x[0:4]
a2=x[4:6]
a3=x[6:]

[1, 2, 3, 4] [5, 6] [7, 8, 9]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
from numpy import random

x=random.randint(10,size=(2,5))
print(x)
x.max(axis=1)

[[1 0 7 4 8]
 [0 4 7 0 2]]


array([8, 7])

### Pandas

Run the following load command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [ ]:
import pandas as pd
def noofuniq(df):
  uniqspecies=df[4].unique()
  return len(uniqspecies)

          0       1       2       3                  4
0    b'5.1'  b'3.5'  b'1.4'  b'0.2'     b'Iris-setosa'
1    b'4.9'  b'3.0'  b'1.4'  b'0.2'     b'Iris-setosa'
2    b'4.7'  b'3.2'  b'1.3'  b'0.2'     b'Iris-setosa'
3    b'4.6'  b'3.1'  b'1.5'  b'0.2'     b'Iris-setosa'
4    b'5.0'  b'3.6'  b'1.4'  b'0.2'     b'Iris-setosa'
..      ...     ...     ...     ...                ...
145  b'6.7'  b'3.0'  b'5.2'  b'2.3'  b'Iris-virginica'
146  b'6.3'  b'2.5'  b'5.0'  b'1.9'  b'Iris-virginica'
147  b'6.5'  b'3.0'  b'5.2'  b'2.0'  b'Iris-virginica'
148  b'6.2'  b'3.4'  b'5.4'  b'2.3'  b'Iris-virginica'
149  b'5.9'  b'3.0'  b'5.1'  b'1.8'  b'Iris-virginica'

[150 rows x 5 columns]
3


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [ ]:
def bin_petal_len(iris_df):
    pet_len = []
    for length in iris_df[2]:
        if length < 3:
            pet_len.append('small')
        elif length >= 3 and length < 5:
            pet_len.append('medium')
        else:
            pet_len.append('large')
    iris_df['pet_len'] = pet_len
    return iris_df

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
import pandas as pd
def mostfreqpl(df):
  return df[2].mode()