Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [53]:
import numpy as np

In [54]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
one = np.array([1, 2, 3, 4, 5])
print(one)
# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
two = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(two)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
# Write a NumPy function to create an array with random values of shape [3,4]
x = np.random.rand(3, 4)
# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
y = np.zeros([3,4])
# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
z = np.ones([3,4])

In [56]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
a = np.arange(1,10,2)
print(a)

[1 3 5 7 9]


### Basic array operations
- algebraic operations
- logical operations

In [57]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [58]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
def add(a,b):
  return np.add(a,b)
def subtr(a,b):
  return np.subtract(a,b)
def mul(a,b):
  return np.multiply(a,b)
def divide(a,b):
  return np.divide(a,b)


In [59]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
def sum0(a):
  return np.sum(a,axis=0)
# Write a NumPy function to get the sum of the array 'a' along axis=1
def sum1(a):
  return np.sum(a,axis=1)

In [60]:
# Write a NumPy function to reverse the array 'a'
np.flip(a)
# Write a NumPy function to reverse the array 'a' along axis=0
np.flip(a,axis=0)
# Write a NumPy function to reverse the array 'a' along axis=1
np.flip(a,axis=1)

array([[ 8,  6, -4],
       [ 1,  3,  9],
       [ 5,  8,  1]])

### Sorting and concatenation
- sort arrays
- join multiple arrays


In [61]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [62]:
# Write a NumPy function to sort the array 'a'
np.sort(a)
# Write a NumPy function to sort the array 'a' along axis=0
np.sort(a,axis=0)
# Write a NumPy function to sort the array 'a' along axis=1
np.sort(a,axis=1)
# Write a NumPy function to sort the array 'a' in descending order along axis=0
np.flip(np.sort(a,axis=0),axis=0)

array([[ 9,  8,  8],
       [ 1,  6,  5],
       [-4,  3,  1]])

In [63]:
# Write a NumPy function to argsort the array along axis=0
np.argsort(a, axis=0)
# Write a NumPy function to argsort the array along axis=1
np.argsort(a, axis=1)

array([[0, 1, 2],
       [2, 1, 0],
       [0, 2, 1]])

In [64]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
np.concatenate((a,b))
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
np.concatenate((a,b),axis=0)
# Note: You can do the same function using stacking, discover and try that :)


array([[-4,  6,  8],
       [ 9,  3,  1],
       [ 1,  8,  5],
       [11, 16, 18],
       [90, 37, 81],
       [61, 48, 75]])

### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [65]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [66]:
# Write a NumPy function to get the Number of dimensions
len(a.shape)
# Write a NumPy function to get the Shape of the array
a.shape
# Write a NumPy function to get the Size of the array
np.size(a)

9

In [67]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
ra = a.reshape(1,9)

In [68]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
ex = np.expand_dims(a, axis=0)
a[np.newaxis,:]

array([[[4, 6, 8],
        [9, 3, 1],
        [1, 8, 5]]])

### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [69]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [70]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
print(a[1])
print(a[(0,2)])
print(a[0:2])


[0 3 1]
0
[[4 6 0]
 [0 3 1]]


In [71]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
b = a[a>4]
print(b)
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
cond1 = lambda x: x >4
cond2 = lambda x: x%2== 0
b=a[cond1(a)&cond2(b)]
print(b)

[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [72]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [73]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
b = np.copy(a)
print(b+1)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [74]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [75]:
# Write a Pandas function to drop rows that contain a missing value.
import pandas as pd
df = pd.DataFrame(iris_2d)
df.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [76]:
# Write a Pandas function to find the correlation between the first two columns.
print(df.iloc[:, 0].corr(df.iloc[:, 1]))

-0.10936924995064937


In [77]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
df[df.columns[2]].describe()

count    150.000000
mean       3.758667
std        1.764420
min        1.000000
25%        1.600000
50%        4.350000
75%        5.100000
max        6.900000
Name: 2, dtype: float64

In [78]:
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
df = pd.DataFrame(iris_2d, columns=['sepal_length', 'sepal_width', 'petal_length', 'petal_width'])
df['volume'] = (np.pi * df['petal_length'] * df['sepal_length']**2) / 3
df.head()

sepal_length  sepal_width  petal_length  petal_width     volume
0           5.1          3.5           1.4          0.2  38.132652
1           4.9          3.0           1.4          0.2  35.200498
2           4.7          3.2           1.3          0.2  30.072372
3           4.6          3.1           1.5          0.2  33.238050
4           5.0          3.6           1.4          0.2  36.651914

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [79]:
x = np.arange(4, dtype=np.int64)
x = np.ones_like(x)
print(x)

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [80]:
x = [1,2,3,4,5,6,7,8,9]
a = x[0:4]
b = x[4:6]
c = x[6:]
print(a,b,c)

[1, 2, 3, 4] [5, 6] [7, 8, 9]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [81]:
x = np.random.rand(2, 5) * 10
max = np.argmax(x, axis=1)
min = np.argmin(x, axis=1)
print(max,min)
print(x)

[1 3] [2 0]
[[7.23050425 9.56762121 5.0002156  6.04682069 7.52929172]
 [5.25139615 7.18106209 6.2906207  8.55909615 7.57097722]]


### Pandas

Run the following load command and solve the following questions

In [82]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [83]:
df = pd.DataFrame(iris, columns=names)
len(df['species'].unique())

3

# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [84]:
import numpy as np
def classify(petal_length):
  if float(str(petal_length.decode('utf-8'))) < 3:
    return 'small'
  elif float(str(petal_length.decode('utf-8'))) < 5:
    return 'medium'
  else:
    return 'large'

textarr = df.iloc[:, 2].apply(classify)
textarr


0      small
1      small
2      small
3      small
4      small
       ...  
145    large
146    large
147    large
148    large
149    large
Name: petallength, Length: 150, dtype: object

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [85]:
df['petallength'].value_counts()

petallength
b'1.5'    14
b'1.4'    12
b'5.1'     8
b'4.5'     8
b'1.6'     7
b'1.3'     7
b'5.6'     6
b'4.7'     5
b'4.9'     5
b'4.0'     5
b'4.2'     4
b'5.0'     4
b'4.4'     4
b'4.8'     4
b'1.7'     4
b'3.9'     3
b'4.6'     3
b'5.7'     3
b'4.1'     3
b'5.5'     3
b'6.1'     3
b'5.8'     3
b'3.3'     2
b'5.4'     2
b'6.7'     2
b'5.3'     2
b'5.9'     2
b'6.0'     2
b'1.2'     2
b'4.3'     2
b'1.9'     2
b'3.5'     2
b'5.2'     2
b'3.0'     1
b'1.1'     1
b'3.7'     1
b'3.8'     1
b'6.6'     1
b'6.3'     1
b'1.0'     1
b'6.9'     1
b'3.6'     1
b'6.4'     1
Name: count, dtype: int64