Instructions for the assignment


*   Fill the codeblocks according to the comments given
*   Hints are given wherever required
*   Please note that copying will not be tolerated, and appropriate action will be taken if we suspect any misconduct.
*   You're welcome to utilize any online resources in case you feel stuck anywhere :-)









# Section A *(2 Marks each)*

## NumPy (Numerical Python)
**bold text**
### Multidimensional array object
- Array is a grid of homogeneous elements which can be indexed in various ways
- Different from Python list which can store different data types
- NumPy stores multidimensional arrays as an instance of **ndarray**



In [374]:
import numpy as np

In [375]:
# Python list to initialize a one dimensional NumPy array of numbers 1 to 5 and then print it
print(np.array([i for i in range(1,6)]))

# Python list to initialize a two dimensional NumPy array of shape [3,3] and then print it
print(np.array([[(i+3*j) for i in range(3)] for j in range(3)]))

[1 2 3 4 5]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [376]:
# Write a NumPy function to create an array with random values of shape [3,4]
print(np.random.rand(3, 4))

# Write a NumPy function to create an array with all elements initialized as zero of shape [3,4]
print(np.zeros((3,4)))

# Write a NumPy function to create an array with all elements initialized as ones of shape [3,4]
print(np.ones((3,4)))

[[0.60846328 0.48299299 0.17880118 0.68621824]
 [0.540357   0.10964324 0.5607655  0.07785678]
 [0.7380992  0.19559387 0.92076966 0.58279752]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [377]:
# Write a NumPy function to create an array containing a range of evenly spaced intervals
# Hint : Use np.arange or np.linspace
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

### Basic array operations
- algebraic operations
- logical operations

In [378]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [379]:
# Write a NumPy function to add, subtract, multiply and divide arrays 'a' and 'b'
print(np.add(a,b),np.subtract(a,b),np.multiply(a,b),np.divide(a,b),sep='\n')

[[ 7 22 26]
 [99 40 82]
 [62 56 80]]
[[-15 -10 -10]
 [-81 -34 -80]
 [-60 -40 -70]]
[[-44  96 144]
 [810 111  81]
 [ 61 384 375]]
[[-0.36363636  0.375       0.44444444]
 [ 0.1         0.08108108  0.01234568]
 [ 0.01639344  0.16666667  0.06666667]]


In [380]:
# Write a NumPy function to get the sum of the array 'a' along axis=0
print(np.sum(a,axis=0))
# Write a NumPy function to get the sum of the array 'a' along axis=1
print(np.sum(a,axis=1))

[ 6 17 14]
[10 13 14]


In [381]:
# Write a NumPy function to reverse the array 'a'
print(np.flip(a))
# Write a NumPy function to reverse the array 'a' along axis=0
print(np.flip(a,axis=0))
# Write a NumPy function to reverse the array 'a' along axis=1
print(np.flip(a,axis=1))

[[ 5  8  1]
 [ 1  3  9]
 [ 8  6 -4]]
[[ 1  8  5]
 [ 9  3  1]
 [-4  6  8]]
[[ 8  6 -4]
 [ 1  3  9]
 [ 5  8  1]]


### Sorting and concatenation
- sort arrays
- join multiple arrays


In [382]:
a = np.array([[-4,6,8], [9, 3, 1], [1, 8, 5]])
b = np.array([[11,16,18], [90, 37, 81], [61, 48, 75]])

In [383]:
# Write a NumPy function to sort the array 'a'
print(np.sort(a))
# Write a NumPy function to sort the array 'a' along axis=0
print(np.sort(a,axis=0))
# Write a NumPy function to sort the array 'a' along axis=1
print(np.sort(a,axis=1))
# Write a NumPy function to sort the array 'a' in descending order along axis=0
print(np.sort(a,axis=0)[::-1,:])

[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[-4  3  1]
 [ 1  6  5]
 [ 9  8  8]]
[[-4  6  8]
 [ 1  3  9]
 [ 1  5  8]]
[[ 9  8  8]
 [ 1  6  5]
 [-4  3  1]]


In [384]:
# Write a NumPy function to argsort the array along axis=0
print(np.argsort(a,axis=0))
# Write a NumPy function to argsort the array along axis=1
print(np.argsort(a,axis=0))

[[0 1 1]
 [2 0 2]
 [1 2 0]]
[[0 1 1]
 [2 0 2]
 [1 2 0]]


In [385]:
# Write a NumPy function to concatenate the arrays 'a' and 'b'
print(np.concatenate((a,b), axis=1))
# Write a NumPy function to concatenate the arrays 'a' and 'b' along axis = 0
print(np.concatenate((a,b), axis=0))
# Note: You can do the same function using stacking, discover and try that :)
print(np.vstack((a,b)))

[[-4  6  8 11 16 18]
 [ 9  3  1 90 37 81]
 [ 1  8  5 61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]
[[-4  6  8]
 [ 9  3  1]
 [ 1  8  5]
 [11 16 18]
 [90 37 81]
 [61 48 75]]


### Reshaping arrays
- the number of dimensions of the array
-  shape of n-dimensional array as a tuple with n elements s.t. $i^{th}$ element is the length of the $i^{th}$ dimension of the array
- total number of elements of the array
- reshapes the array
- flattens multidimensional array into a 1D array
- adds new dimensions to the array

In [386]:
a = np.array([[4,6,8], [9, 3, 1], [1, 8, 5]])

In [387]:
# Write a NumPy function to get the Number of dimensions
print(a.ndim)
# Write a NumPy function to get the Shape of the array
print(a.shape)
# Write a NumPy function to get the Size of the array
print(a.size)

2
(3, 3)
9


In [388]:
# Write a NumPy function to Reshape the array 'a' to the dimension (1,9)
print(np.reshape(a,newshape=(1,9)))

[[4 6 8 9 3 1 1 8 5]]


In [389]:
# Write a NumPy function to add a new axis to the array 'a'
# Note : Show atleast two different ways of doing this
print(np.reshape(a,newshape=(1,3,3)))
print(np.expand_dims(a,axis=0))

[[[4 6 8]
  [9 3 1]
  [1 8 5]]]
[[[4 6 8]
  [9 3 1]
  [1 8 5]]]


### Indexing and slicing
- NumPy allows indexing array using tuple of nonnegative integers, booleans, array or integers

In [390]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [391]:
# Write a NumPy function to index and slice NumPy arrays similar to Python lists
# Show all three - indexing by a integer, indexing by a tuple, using range
print(a[0])
print(a[(0,1)])
print(a[0,0:2])

[4 6 0]
6
[4 6]


In [392]:
# Write a NumPy function to select values satisfying a specific condition like Values greater than 4
print(a[a>4])
# Write a NumPy function to select values satisfying mulitple conditions like Values greater than 4 and divisible by 2
print(a[(a>4) & (a%2==0)])

[6 8 5]
[6 8]


### Copying arrays
- new array object with a copy of the data
- Changes made in the copy array is not reflected in the original array

In [393]:
a = np.array([[4,6,0], [0, 3, 1], [1, 8, 5]])

In [394]:
# Write a NumPy function to copy the array 'a' and finally print an array where all elements are increased by 1
print(np.copy(a)+1)

[[5 7 1]
 [1 4 2]
 [2 9 6]]


## Pandas ( Python Data Analysis Library)

### Main Features
- Easy handling of missing data in both floating point and non-floating point data.
- Automatic and explicit data alignment, making it easy to perform computations and transformations on data sets.



#### Generating the dataset

Run the following load command to get the 2-Dim iris dataset. Do the following operations on it and please dont edit this cell

In [395]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#### Basic Data Analysis

In [396]:
import pandas as pd
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
# Write a Pandas function to drop rows that contain a missing value.
df = pd.DataFrame(data=iris_2d, columns=names[:4])
df.head()

sepallength  sepalwidth  petallength  petalwidth
0          5.1         3.5          1.4         0.2
1          4.9         3.0          1.4         0.2
2          4.7         3.2          1.3         0.2
3          4.6         3.1          1.5         0.2
4          5.0         3.6          1.4         0.2

In [397]:
# Write a Pandas function to find the correlation between the first two columns.
print(df[names[0]].corr(df[names[1]]))

-0.10936924995064937


In [398]:
# Write a Pandas function to find the mean, median and standard deviation of column 3.
print(df[names[2]].mean(),df[names[2]].median(),df[names[2]].std(),sep='\n')

3.758666666666666
4.35
1.7644204199522626


In [399]:
import math
# Write a Pandas function to create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3
# Hints:
# 1. Introduce new dimension to match iris_2d's
# 2. Add the new column
df["volume"] = math.pi*df["petallength"]*df["sepallength"]*df["sepallength"]/3
df.head()

sepallength  sepalwidth  petallength  petalwidth     volume
0          5.1         3.5          1.4         0.2  38.132652
1          4.9         3.0          1.4         0.2  35.200498
2          4.7         3.2          1.3         0.2  30.072372
3          4.6         3.1          1.5         0.2  33.238050
4          5.0         3.6          1.4         0.2  36.651914

# Section B *(2 Marks each)*

###NumPy

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [400]:
x = np.arange(4, dtype=np.int64)
print(np.ones(x.shape, dtype=x.dtype))

[1 1 1 1]


Q2 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [401]:
x = np.arange(1,10, dtype=np.int64)
print(np.split(x,(4,6)))

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9])]


Q3 Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [402]:
x = np.random.randint(0, 10, size=(2, 5))
print(x)
print(np.max(x,axis=1))
print(np.argmax(x, axis=1))
print(np.min(x,axis=1))
print(np.argmin(x, axis=1))

[[1 7 5 5 4]
 [1 3 3 3 7]]
[7 7]
[1 4]
[1 1]
[0 0]


### Pandas

Run the following load command and solve the following questions

In [403]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

Q4 Write a Pandas function to find the count of unique species.

In [404]:
df = pd.DataFrame(data=iris, columns=names)
print(df['species'].nunique())

3


# Q5 Write a Pandas function to bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
- Less than 3 –> ‘small’
- 3-5 –> ‘medium’
- greater than equal to 5 –> ‘large’

In [405]:
df["petallength_bin"]=pd.cut(df["petallength"].astype('float'), [-1,2.99,4.99,float('inf')], labels=['small','medium','large'])
df.head()

sepallength sepalwidth petallength petalwidth         species  \
0      b'5.1'     b'3.5'      b'1.4'     b'0.2'  b'Iris-setosa'   
1      b'4.9'     b'3.0'      b'1.4'     b'0.2'  b'Iris-setosa'   
2      b'4.7'     b'3.2'      b'1.3'     b'0.2'  b'Iris-setosa'   
3      b'4.6'     b'3.1'      b'1.5'     b'0.2'  b'Iris-setosa'   
4      b'5.0'     b'3.6'      b'1.4'     b'0.2'  b'Iris-setosa'   

  petallength_bin  
0           small  
1           small  
2           small  
3           small  
4           small

Q6 Write a Pandas function to find the most frequent value of petal length (3rd column) in iris dataset

In [406]:
print(df['petallength'].value_counts().nlargest(1), df['petallength_bin'].value_counts().nlargest(1), sep='\n')

petallength
b'1.5'    14
Name: count, dtype: int64
petallength_bin
medium    54
Name: count, dtype: int64
